package com.shopme.checkout.phonepe;

public enum PhonePeResponseCodes {
	PAYMENT_SUCCESS, BAD_REQUEST,AUTHORIZATION_FAILED, 
	INTERNAL_SERVER_ERROR, TRANSACTION_NOT_FOUND, PAYMENT_ERROR, PAYMENT_PENDING,
	PAYMENT_DECLINED, TIMED_OUT
}
